AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Book details of a visit, using Amazon Lex to perform natural language
  understanding
Resources:
  JarvisValidation:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: >-
        Book details of a visit, using Amazon Lex to perform natural language
        understanding
      MemorySize: 128
      Timeout: 10
      Role: >-
        arn:aws:iam::963100174055:role/service-role/JarvisValidation-role-y9jcmjfb
      Tags:
        'lambda-console:blueprint': lex-book-trip-python
